### PR TITLE
Optimization - replace typedefs in `Ast.hx` with `@:structInit` classes

### PR DESCRIPTION
**Pull request by ShaharMS**
This can boost performance on static targets, since typedefs are compiled down to dynamic objects, which are known to be slow.

### CODE REVIEW

**Comment by ShaharMS** [comment]
i dont really understand why CI is failing, it seems like it doesnt even relate to my changes (it fails while trying to install haxe nightly)

**Comment by PXshadow** [comment]
> 

I have not seen that happen before, hopefully it's just a Haxelib server or github one time issue

**Comment by ShaharMS** [comment]
ill turn this into a draft, and revisit this when its more relevant (for example, when go2hx is advanced enough that it needs to start worrying about optimizing for speed)

**Comment by PXshadow** [comment]
> ill turn this into a draft, and revisit this when its more relevant (for example, when go2hx is advanced enough that it needs to start worrying about optimizing for speed)

There is also a technical limitation of this pr. Haxe's json does not support json decoding to a Class. Json is the communication language between the Golang part of the compiler to the Haxe part.

The introduction of the compiler being able to be compiled into nodejs, has made the json decoding extremely fast, and I have found no better alternatives. 

If no new developments are to be brought up I think we should close this. @ShaharMS  I'm interested in your thoughts, as ell as @elliott5 .

**Comment by elliott5** [comment]
I look forward to the time when we can compile the Go component of the system (go4hx)  into Haxe so that code can be integrated into a pure Haxe code-base. At that point using JSON between the Go & Haxe parts of the Go->Haxe translation process will not be required, and the ideas in this PR could be implemented ... unfortunately that exalted future state of this project is still some way off as I write these words.

**Comment by ShaharMS** [comment]
Thanks for your input :). Iirc, the initial goal of this pr was to boost go2hx without making a mess by making the typedefs structInit classes. I thought that would let us keep everything the same, but looks like it wouldn't...

If implementing this won't give any real performance increase, or even irrelevant for the current state of the project, I think this shouldd be closed.

**Pull request closed without merging**
